Repository zeabur/zeabur, pull requests merged in 2023-11, with the labels that each got.

#232 docs: Documentation for backup feature
  docs/pages/deploy/_meta.en-US.json
  docs/pages/deploy/_meta.zh-CN.json
  docs/pages/deploy/_meta.zh-TW.json
  docs/pages/deploy/backup.en-US.mdx
  docs/pages/deploy/backup.zh-CN.mdx
  docs/pages/deploy/backup.zh-TW.mdx
  docs/public/deploy/backup/backup-created.png
  docs/public/deploy/backup/backup-files.png
  docs/public/deploy/backup/backup-not-suspend.png
  docs/public/deploy/backup/backup-success.png
  docs/public/deploy/backup/backup-suspend-service.png
  docs/public/deploy/backup/backup-tab.png
Labels: documentation

#234 feat: add langfuse
  prebuilts/langfuse.toml
Labels: prebuilt

#236 feat(prebuilt): add rabbitmq:3-management
  prebuilts/rabbitmq.toml
Labels: prebuilt

#233 feat: add ferretdb
  prebuilts/ferretdb.toml
Labels: prebuilt

#237 feat(docs/rabbitmq.toml) RabbitMq Docs/ Web
  docs/pages/databases/rabbitmq.en-US.mdx
  docs/pages/databases/rabbitmq.zh-CN.mdx
  docs/pages/databases/rabbitmq.zh-TW.mdx
  prebuilts/rabbitmq.toml
Labels: documentation

#239 fix: trying to fix twitter card
  docs/pages/_document.js
Labels: bug

#241 fix: invalid dns image
  docs/pages/deploy/domain-binding.en-US.mdx
  docs/pages/deploy/domain-binding.zh-CN.mdx
  docs/pages/deploy/domain-binding.zh-TW.mdx
  docs/public/deploy/domain/invalid-dns.png
Labels: documentation

#243 Add etcd into prebuild
  prebuilts/etcd.toml
Labels: prebuilt

#250 docs: fix GitHub typo
  docs/pages/integration/_meta.en-US.json
  docs/pages/integration/_meta.zh-CN.json
  docs/pages/integration/_meta.zh-TW.json
  docs/pages/marketplace/ttrss.en-US.mdx
  docs/pages/marketplace/ttrss.zh-CN.mdx
  docs/pages/marketplace/ttrss.zh-TW.mdx
Labels: documentation

#252 fix: rabbitmq docs
  docs/pages/databases/rabbitmq.en-US.mdx
  docs/pages/databases/rabbitmq.zh-CN.mdx
  docs/pages/databases/rabbitmq.zh-TW.mdx
Labels: bug, documentation

#251 docs: add network pricing
  docs/pages/billing/pricing.en-US.mdx
  docs/pages/billing/pricing.zh-CN.mdx
  docs/pages/billing/pricing.zh-TW.mdx
Labels: documentation

#254 新增文件內容:「## 部屬nodejs時,額外注意事項」 在 docs/pages/guides/nodejs.zh-TW.mdx 最下方
  docs/pages/guides/nodejs.zh-TW.mdx
Labels: documentation

#255 docs: nodejs additional notes
  docs/pages/guides/nodejs.en-US.mdx
  docs/pages/guides/nodejs.zh-CN.mdx
Labels: documentation

#258 feat: add Focalboard
  prebuilts/focalboard.toml
Labels: prebuilt

#240 docs: Special variables
  docs/pages/deploy/customize-prebuilt.en-US.mdx
  docs/pages/deploy/customize-prebuilt.zh-CN.mdx
  docs/pages/deploy/customize-prebuilt.zh-TW.mdx
  docs/pages/deploy/special-variables.en-US.mdx
  docs/pages/deploy/special-variables.zh-CN.mdx
  docs/pages/deploy/special-variables.zh-TW.mdx
  docs/public/deploy/customize-prebuilt/mariadb-config-example.png
  docs/public/deploy/customize-prebuilt/open-customize.png
  docs/public/deploy/customize-prebuilt/prebuilt-config-page.png
  docs/public/deploy/special-variables/domain-port-customization.png
Labels: documentation

#256 Docs/refactor
  docs/pages/_meta.en-US.json
  docs/pages/_meta.zh-CN.json
  docs/pages/_meta.zh-TW.json
  docs/pages/databases/_meta.en-US.json
  docs/pages/databases/_meta.zh-CN.json
  docs/pages/databases/_meta.zh-TW.json
  docs/pages/deploy/github.en-US.mdx
  docs/pages/deploy/github.zh-CN.mdx
  docs/pages/deploy/github.zh-TW.mdx
  docs/pages/integration/_meta.en-US.json
  docs/pages/integration/_meta.zh-CN.json
  docs/pages/integration/_meta.zh-TW.json
  docs/pages/marketplace/mongodb.en-US.mdx
  docs/pages/marketplace/mongodb.zh-CN.mdx
  docs/pages/marketplace/mongodb.zh-TW.mdx
  docs/pages/marketplace/mysql.en-US.mdx
  docs/pages/marketplace/mysql.zh-CN.mdx
  docs/pages/marketplace/mysql.zh-TW.mdx
  docs/pages/marketplace/postgresql.en-US.mdx
  docs/pages/marketplace/postgresql.zh-CN.mdx
  docs/pages/marketplace/postgresql.zh-TW.mdx
  docs/pages/marketplace/rabbitmq.en-US.mdx
  docs/pages/marketplace/rabbitmq.zh-CN.mdx
  docs/pages/marketplace/rabbitmq.zh-TW.mdx
  docs/pages/marketplace/redis.en-US.mdx
  docs/pages/marketplace/redis.zh-CN.mdx
  docs/pages/marketplace/redis.zh-TW.mdx
Labels: documentation

#260 docs: sponsor
  docs/pages/billing/_meta.en-US.json
  docs/pages/billing/_meta.zh-CN.json
  docs/pages/billing/_meta.zh-TW.json
  docs/pages/billing/sponsor.en-US.mdx
  docs/pages/billing/sponsor.zh-CN.mdx
  docs/pages/billing/sponsor.zh-TW.mdx
Labels: documentation

#262 Update django.zh-CN.mdx
  docs/pages/guides/python/django.zh-CN.mdx
Labels: documentation

#263 feat(prebuilt/postgre): Upgrade to 16
  prebuilts/postgresql.toml
Labels: prebuilt

#264 docs: add guide for banner resource
  docs/pages/billing/sponsor.en-US.mdx
  docs/pages/billing/sponsor.zh-CN.mdx
  docs/pages/billing/sponsor.zh-TW.mdx
Labels: documentation
