Repository zeabur/zeabur, pull requests merged in 2023-07, with the labels that each got.

#135 docs: deploy uptime kuma
  docs/pages/marketplace/uptime-kuma.en-US.mdx
  docs/public/marketplace/uptime-kuma/configure.png
  docs/public/marketplace/uptime-kuma/dashboard.png
  docs/public/marketplace/uptime-kuma/deploy.png
  docs/public/marketplace/uptime-kuma/domain.png
  docs/public/marketplace/uptime-kuma/monitoring-setup.png
  docs/public/marketplace/uptime-kuma/monitoring.png
Labels: documentation

#136 chore: add template button in deploy doc
  docs/pages/marketplace/uptime-kuma.en-US.mdx
  docs/public/marketplace/uptime-kuma/template.png
Labels: documentation

#139 feat(marketplace): Add n8n to marketplace
  marketplace/n8n.json
Labels: enhancement, marketplace

#137 fix: add placeholder for uptime kuma doc
  docs/pages/marketplace/uptime-kuma.zh-CN.mdx
  docs/pages/marketplace/uptime-kuma.zh-TW.mdx
Labels: bug, documentation

#142 docs: marketplace/memos
  docs/pages/marketplace/memos.en-US.mdx
  docs/pages/marketplace/memos.zh-CN.mdx
  docs/pages/marketplace/memos.zh-TW.mdx
  docs/public/marketplace/memos/deploy.png
  docs/public/marketplace/memos/domain.png
Labels: documentation

#144 fix: fixing a typo
  docs/pages/marketplace/rsshub.zh-TW.mdx
Labels: documentation

#151 docs: n8n en-US docs
  docs/pages/marketplace/n8n.en-US.mdx
  docs/pages/marketplace/n8n.zh-CN.mdx
  docs/pages/marketplace/n8n.zh-TW.mdx
  docs/public/marketplace/n8n/deploy.png
  docs/public/marketplace/n8n/finish.png
  docs/public/marketplace/n8n/setup.png
  docs/public/marketplace/postgresql/connect.png
  docs/public/marketplace/postgresql/deploy.png
Labels: documentation

#153 docs: referral documentations
  docs/pages/billing/_meta.en-US.json
  docs/pages/billing/_meta.zh-CN.json
  docs/pages/billing/_meta.zh-TW.json
  docs/pages/billing/referral.en-US.mdx
  docs/pages/billing/referral.zh-CN.mdx
  docs/pages/billing/referral.zh-TW.mdx
  docs/public/referral/referral.png
Labels: documentation
