Repository zeabur/zeabur, pull requests merged in 2024-01, with the labels that each got.

#297 ZEA-2369: Add dragonflyDB prebuilt config
  prebuilts/dragonfly.toml
Labels: prebuilt

#298 chore: update memos version to 0.18.1
  prebuilts/memos.toml
Labels: prebuilt

#299 fix: deploy meta
  docs/pages/deploy/_meta.en-US.json
  docs/pages/deploy/_meta.js-JP.json
  docs/pages/deploy/_meta.zh-CN.json
  docs/pages/deploy/_meta.zh-TW.json
Labels: bug, documentation

#302 ZEA-2367: Add dragonfly doc
  docs/pages/marketplace/dragonfly.en-US.mdx
  docs/pages/marketplace/dragonfly.ja-JP.mdx
  docs/pages/marketplace/dragonfly.zh-CN.mdx
  docs/pages/marketplace/dragonfly.zh-TW.mdx
  docs/public/databases/dragonfly/client-dragonfly.en-US.png
  docs/public/databases/dragonfly/connection-dragonfly.en-US.png
  docs/public/databases/dragonfly/deploy-dragonfly.en-US.png
  docs/public/deploy/common/select-prebuilt-service.en-US.png
Labels: documentation

#304 prebuilt: fix icon for umami
  prebuilts/unami.toml
Labels: bug, prebuilt

#303 ZEA-2385: Documentation for generate apikey
  docs/pages/_meta.en-US.json
  docs/pages/_meta.ja-JP.json
  docs/pages/_meta.zh-CN.json
  docs/pages/_meta.zh-TW.json
  docs/pages/developer/_meta.en-US.json
  docs/pages/developer/_meta.js-JP.json
  docs/pages/developer/_meta.zh-CN.json
  docs/pages/developer/_meta.zh-TW.json
  docs/pages/developer/use-api-key.en-US.mdx
  docs/pages/developer/use-api-key.ja-JP.mdx
  docs/pages/developer/use-api-key.zh-CN.mdx
  docs/pages/developer/use-api-key.zh-TW.mdx
  docs/public/developer/api-key/copy-api-key.en-US.png
  docs/public/developer/api-key/developer.en-US.png
  docs/public/developer/api-key/generate-api-key.en-US.png
  docs/public/developer/api-key/view-api-key.en-US.png
Labels: documentation, enhancement

#306 chore: locales for credits and danger zone
  dashboard/locales/en-US/billing.json
  dashboard/locales/en-US/service.json
  dashboard/locales/zh-CN/billing.json
  dashboard/locales/zh-CN/service.json
  dashboard/locales/zh-TW/billing.json
  dashboard/locales/zh-TW/service.json
Labels: locales

#307 fix: duplicated og
  docs/pages/_document.js
Labels: bug

#305 Docs/developer open api
  docs/pages/developer/_meta.en-US.json
  docs/pages/developer/_meta.ja-JP.json
  docs/pages/developer/_meta.js-JP.json
  docs/pages/developer/_meta.zh-CN.json
  docs/pages/developer/_meta.zh-TW.json
  docs/pages/developer/public-api.en-US.mdx
  docs/pages/developer/public-api.ja-JP.mdx
  docs/pages/developer/public-api.zh-CN.mdx
  docs/pages/developer/public-api.zh-TW.mdx
Labels: documentation

#311 prebuilt: librechat
  prebuilts/librechat.toml
Labels: prebuilt

#312 fix: LibreChat docker image
  prebuilts/librechat.toml
Labels: bug, prebuilt

#314 docs: add redis deploy docs
  docs/pages/marketplace/redis.en-US.mdx
  docs/pages/marketplace/redis.ja-JP.mdx
  docs/pages/marketplace/redis.zh-CN.mdx
  docs/pages/marketplace/redis.zh-TW.mdx
  docs/public/databases/redis/deploy-redis.gif
  docs/public/databases/redis/redis-connect-path.png
  docs/public/databases/redis/redis-test-connection.png
Labels: documentation

#313 ZEA-2452: Add guide of how to use config
  docs/pages/deploy/_meta.en-US.json
  docs/pages/deploy/_meta.js-JP.json
  docs/pages/deploy/_meta.zh-CN.json
  docs/pages/deploy/_meta.zh-TW.json
  docs/pages/deploy/config-edit.en-US.mdx
  docs/pages/deploy/config-edit.ja-JP.mdx
  docs/pages/deploy/config-edit.zh-CN.mdx
  docs/pages/deploy/config-edit.zh-TW.mdx
  docs/public/deploy/config-edit/create-new-config.en-US.png
  docs/public/deploy/config-edit/create-nginx-service.en-US.png
  docs/public/deploy/config-edit/create-vultwarden-service.en-US.png
  docs/public/deploy/config-edit/open-config-editor.en-US.png
  docs/public/deploy/config-edit/restart-service.en-US.png
  docs/public/deploy/config-edit/save-config.en-US.png
  docs/public/deploy/config-edit/vultwarden-service.en-US.png
Labels: documentation, enhancement

#317 docs: fix build error due to import image from public
  docs/pages/marketplace/redis.zh-CN.mdx
Labels: bug, documentation

#318 docs(guides/python): Typo
  docs/pages/guides/python.zh-TW.mdx
Labels: documentation

#320 prebuilt: add flowise
  prebuilts/flowise.toml
Labels: prebuilt

#321 Update flowise.toml
  prebuilts/flowise.toml
Labels: bug

#323 add start cmd and args for flowise
  prebuilts/flowise.toml
Labels: bug, prebuilt

#325 docs: deploy flowise
  docs/pages/marketplace/botwayce.en-US.mdx
  docs/pages/marketplace/botwayce.zh-CN.mdx
  docs/pages/marketplace/botwayce.zh-TW.mdx
  docs/pages/marketplace/flowise.en-US.mdx
  docs/pages/marketplace/flowise.ja-JP.mdx
  docs/pages/marketplace/flowise.zh-CN.mdx
  docs/pages/marketplace/flowise.zh-TW.mdx
  docs/pages/marketplace/memos.en-US.mdx
  docs/pages/marketplace/memos.zh-TW.mdx
  docs/public/marketplace/flowise/prebuilt.png
Labels: documentation

#327 prebuilts: deprecate artalk and hoppscotch
  prebuilts/artalk.toml
  prebuilts/hoppscotch.toml
Labels: prebuilt

#326 docs: deprecate environment document folder
  docs/pages/_meta.en-US.json
  docs/pages/_meta.ja-JP.json
  docs/pages/_meta.zh-CN.json
  docs/pages/_meta.zh-TW.json
  docs/pages/deploy/_meta.en-US.json
  docs/pages/deploy/_meta.ja-JP.json
  docs/pages/deploy/_meta.zh-CN.json
  docs/pages/deploy/_meta.zh-TW.json
  docs/pages/deploy/preview.en-US.mdx
  docs/pages/deploy/preview.ja-JP.mdx
  docs/pages/deploy/preview.zh-CN.mdx
  docs/pages/deploy/preview.zh-TW.mdx
  docs/pages/deploy/variables.en-US.mdx
  docs/pages/deploy/variables.ja-JP.mdx
  docs/pages/deploy/variables.zh-CN.mdx
  docs/pages/deploy/variables.zh-TW.mdx
  docs/pages/environment/_meta.en-US.json
  docs/pages/environment/_meta.ja-JP.json
  docs/pages/environment/_meta.zh-CN.json
  docs/pages/environment/_meta.zh-TW.json
  docs/pages/environment/multi-env.en-US.mdx
  docs/pages/environment/multi-env.ja-JP.mdx
  docs/pages/environment/multi-env.zh-CN.mdx
  docs/pages/environment/multi-env.zh-TW.mdx
Labels: documentation
