Repository zeabur/zeabur, pull requests merged in 2024-02, with the labels that each got.

#332 fix wrong links to variable doc in get started page
  docs/pages/get-started.en-US.mdx
  docs/pages/get-started.ja-JP.mdx
  docs/pages/get-started.zh-CN.mdx
  docs/pages/get-started.zh-TW.mdx
Labels: bug, documentation

#333 docs(guides/java): Add JVM args & environment settings
  docs/pages/guides/java.en-US.mdx
  docs/pages/guides/java.ja-JP.mdx
  docs/pages/guides/java.zh-CN.mdx
  docs/pages/guides/java.zh-TW.mdx
Labels: documentation

#340 docs: fix typo in nodejs guide
  docs/pages/guides/nodejs.en-US.mdx
Labels: bug, documentation

#341 docs: delete useless contents in zh-CN logto document
  docs/pages/marketplace/logto.zh-CN.mdx
Labels: documentation

#342 docs: fix image description bug in rabbitmq doc
  docs/pages/marketplace/rabbitmq.zh-CN.mdx
  docs/pages/marketplace/rabbitmq.zh-TW.mdx
Labels: documentation

#343 feat(prebuilts): Add Actual
  prebuilts/actual.toml
Labels: prebuilt
